# Generated by Django 5.0.6 on 2024-05-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moglix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headermodel',
            name='ancher',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
