# Generated by Django 5.0.6 on 2024-05-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moglix', '0002_headermodel_ancher'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarEnergyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
