# Generated by Django 5.0.6 on 2024-05-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moglix', '0003_solarenergydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarenergydata',
            name='sub_head',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
