# Generated by Django 5.0.6 on 2024-05-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moglix', '0004_solarenergydata_sub_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarenergydata',
            name='target',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
